name: Cloudflare Pages PR Preview

on:
  pull_request_target:
    types: [opened, synchronize, labeled]
    paths:
      - 'apps/remix/**'
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    if: |
      (((github.event.action == 'labeled') && 
        (github.event.label.name == 'preview')) ||
      ((github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'preview'))) &&
      ( vars.ENABLE_CF_PAGES == 'true' )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: SPA Build
        run: pnpm run -C ./apps/remix spa-preview

      - name: Deploy
        uses: cloudflare/pages-action@v1
        id: deploy-cloudflare-pages
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          projectName: ${{ vars.CF_PROJECT_NAME }}
          directory: 'apps/remix/build/client/'
          branch: ${{ github.event.pull_request.head.ref }}
      - name: Comment preview deployed successful
        if: ${{ github.event.workflow_run.event != 'push' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cloudflare-pages-preview-deployment
          message: |
            ## <span aria-hidden="true">âœ…</span> Preview Deployed Successfully!
            | Name | Link |
            | ---- | ---- |
            | **Latest commit** | ${{ github.sha }} |
            | **Latest deploy log** | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | **Preview URL (Latest)** | ${{ steps.deploy-cloudflare-pages.outputs.url }} |
            | **Preview URL (Branch)** | ${{ steps.deploy-cloudflare-pages.outputs.alias }} |
          